# Generated by Django 2.2.15 on 2020-08-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Ingrese el contenido'),
            preserve_default=False,
        ),
    ]
